services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/sugar-tracker
      - "bundle:/usr/local/bundle"
    command: rails s -b 0.0.0.0
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: password

volumes:
  bundle:
  postgres_data:
